[project]
name = "capybara"
version = "0.1.0"
description = "Financial Policies of various financial institutions."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "docling>=2.94.0",
    "loguru>=0.7.3",
    "pathlib>=1.0.1",
    "selenium>=4.44.0",
]

[project.optional-dependencies]
dev = [
    "pre-commit>=4.6.0",
    "ruff>=0.15.15",
]

[tool.ruff]
extend-exclude = ["Justfile", "pyproject.toml"]

[tool.ruff.lint]
ignore = [
    "W191", # Ignore tab indentation rules (handled by specific file types)
    "E111", # Ignore indentation errors
]
